### ISSUE TITLE
Why does this repo use `just`? What does it do better than `nix run`?

### ISSUE THREAD

**Issue by hab25** [emacs-twist/twist.nix#138]

**Comment by akirak** [comment]
@hab25 Did you have a look at the content of `justfile`? It basically runs a bunch of `nix` commands with varying options. It would be possible to wrap them in several `apps`/`packages` in the flake, but that would require more boilerplate code. I use `just` simply because I thought that would make the configuration more concise. Actually, those tasks were initially in the GitHub workflow, but I moved them to `justfile` to make it portable. `just` is only used for testing, so it does not add a runtime dependency for users.

**Comment by akirak** [comment]
> the learning floor when contributing to those tests

If someone finds the `justfile` in this repository too difficult to understand, I don't think he/she can contribute to the Nix code of this project. I learned it in three minutes or so, faster than composing this message to you. The problem would be documentation though, I'll need to write a contribution guide, if I want contributions.

> the potential for malware

If `just` is installed from nixpkgs, it is reviewed by a package maintainer on every package upgrade, rather than blindly fetching the latest revision from Git. You can't use NixOS without basically trusting this process. This project assumes GNU Emacs and most packages (that are manually reviewed) from nixpkgs are safe. 

It's also run on CI, so the user doesn't necessarily have to run it locally.

> the potential sources of bugs

Nix isn't bug-free, either. `casey/just` has 196 open issues now, while `nixos/nix` has 2.6k. They can't be directly compared for many reasons, but Nix itself is quite a potential source of bugs! I use Nix not because it doesn't have a bug, but because there are benefits of using it even if it has some bugs. You could have bugs even without writing shell scripts by your hand, and I use `just` for developer experience, to resolve bugs in this project efficiently.

> disk space

`just` is very small in instalation size. On the other hand, building a Nix derivation consumes storage every time any of its inputs change. The storage space used by `just` is negligible here.

> My opinion is that implementing the functionality of just that this project uses in nix is so trivial and requires so little code (i.e., probably just a few let-binds to share common commands) that it is not worth the additional dependency.

I don't want to further complicate `flake.nix` in `test` directory, so it's meaningful to keep them separate. Putting them in `flake.nix` also brings a risk of accidentally running the test suite from outside of the project tree.

**Comment by akirak** [comment]
> a fair number of people want this and there's a related open issue https://github.com/NixOS/nix/issues/8034.

Thank you for the pointer. I don't always stay up-to-date with the current status of Nix and its ecosystem.
