### ISSUE TITLE
Should parser be case-insensitive?

### ISSUE THREAD

**Issue by terlar** [emacs-twist/twist.nix#63]
I ran into the dired-hacks packages using `Package-requires:` instead of `Package-Requires:` and because of that the dependency resolution didn't work.

I created a PR to fix this:
https://github.com/Fuco1/dired-hacks/pull/194/files

But perhaps the parser should be case-insensitive?

**Comment by akirak** [comment]
[The manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html) doesn't explicitly state about case-sensitiveness, but `lisp-mnt.el`, which is used by `package.el`, performs search with `case-fold-search` set to t. For compatibility with the existing ecosystem for Emacs, it will be better to follow the implementation.

I personally didn't want this change, because Nix's `builtins.match` supports no option. It will be done in a tedious (and ugly) way like `[Pp][Aa][Cc][Kk][Aa][Gg][Ee]-[Rr][Ee][Qq][Uu][Ii][Rr][Ee][Ss]`. But we should do it. I will make the change. Thanks.
